/*
 * The MIT License
 *
 * Copyright 2024 samueladebowale.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.cometbid.sample.ecommerce.api.order;

import static java.util.stream.Collectors.toList;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;
import java.time.ZoneOffset;
import java.util.List;
import java.util.Objects;
import java.util.stream.StreamSupport;
import org.cometbid.sample.ecommerce.api.address.AddressRepresentationModelAssembler;
import org.cometbid.sample.ecommerce.api.entity.OrderEntity;
import org.cometbid.sample.ecommerce.user.api.hateoas.CustomerRepresentationModelAssembler;
import org.cometbid.sample.ecommerce.user.api.service.ItemService;
import org.cometbid.swaggerCodeGen.model.Order;
import org.springframework.beans.BeanUtils;
import org.springframework.hateoas.server.mvc.RepresentationModelAssemblerSupport;
import org.springframework.stereotype.Component;

/**
 *
 * @author samueladebowale
 */
@Component
public class OrderRepresentationModelAssembler extends
        RepresentationModelAssemblerSupport<OrderEntity, Order> {

    private final CustomerRepresentationModelAssembler uAssembler;
    private final AddressRepresentationModelAssembler aAssembler;
    private final CardRepresentationModelAssembler cAssembler;
    private final ShipmentRepresentationModelAssembler sAssembler;
    private final ItemService itemService;

    /**
     * Creates a new {@link RepresentationModelAssemblerSupport} using the given
     * controller class and resource type.
     * @param uAssembler
     * @param aAssembler
     * @param cAssembler
     * @param sAssembler
     * @param itemService
     */
    public OrderRepresentationModelAssembler(CustomerRepresentationModelAssembler uAssembler,
            AddressRepresentationModelAssembler aAssembler, CardRepresentationModelAssembler cAssembler,
            ShipmentRepresentationModelAssembler sAssembler, ItemService itemService) {

        super(OrderController.class, Order.class);
        this.uAssembler = uAssembler;
        this.aAssembler = aAssembler;
        this.cAssembler = cAssembler;
        this.sAssembler = sAssembler;
        this.itemService = itemService;
    }

    /**
     * Coverts the Order entity to resource
     *
     * @param entity
     */
    @Override
    public Order toModel(OrderEntity entity) {
        System.out.println("\n\n\nentity = " + entity);

        Order resource = createModelWithId(entity.getId(), entity);
        BeanUtils.copyProperties(entity, resource);

        resource.id(entity.getId().toString())
                .customer(uAssembler.toModel(entity.getUserEntity()))
                .shipment(sAssembler.toModel(entity.getShipment())) 
                //.address(aAssembler.toModel(entity.getAddressEntity()))
                .card(cAssembler.toModel(entity.getCardEntity()))
                .items(itemService.toModelList(entity.getItems()))
                .date(entity.getOrderDate().toInstant().atOffset(ZoneOffset.UTC));

        System.out.println("resource = " + resource);
        // Self link generated by createModelWithId has missing api path. Therefore, generating additionally.
        // can be removed once fixed.
        resource.add(linkTo(methodOn(OrderController.class).getByOrderId(entity.getId().toString()))
                .withSelfRel());
        return resource;
    }

    /**
     * Coverts the collection of Product entities to list of resources.
     *
     * @param entities
     * @return 
     */
    public List<Order> toListModel(Iterable<OrderEntity> entities) {
        if (Objects.isNull(entities)) {
            return List.of();
        }
        return StreamSupport.stream(entities.spliterator(), false).map(this::toModel)
                .collect(toList());
    }

}
