/*
 * The MIT License
 *
 * Copyright 2024 samueladebowale.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.cometbid.sample.ecommerce.user.api.hateoas;

import static java.util.stream.Collectors.toList;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.linkTo;
import static org.springframework.hateoas.server.mvc.WebMvcLinkBuilder.methodOn;
import java.util.List;
import java.util.Objects;
import java.util.stream.StreamSupport;
import org.cometbid.sample.ecommerce.api.customer.CustomerController;
import org.cometbid.sample.ecommerce.api.customer.CustomerEntity;
import org.cometbid.swaggerCodeGen.model.Customer;
import org.springframework.beans.BeanUtils;
import org.springframework.hateoas.server.mvc.RepresentationModelAssemblerSupport;
import org.springframework.stereotype.Component;

/**
 *
 * @author samueladebowale
 */
@Component
public class CustomerRepresentationModelAssembler extends RepresentationModelAssemblerSupport<CustomerEntity, Customer> {

    /**
     * Creates a new {@link RepresentationModelAssemblerSupport} using the given
     * controller class and resource type.
     */
    public CustomerRepresentationModelAssembler() {
        super(CustomerController.class, Customer.class);
    }

    /**
     * Converts the Customer entity to resource
     *
     * @param entity
     */
    @Override
    public Customer toModel(CustomerEntity entity) {
        Customer resource = createModelWithId(entity.getId(), entity);
        BeanUtils.copyProperties(entity, resource);
        resource.setId(entity.getId());

        // Self link generated by createModelWithId has missing api path. Therefore,
        // generating additionally.
        // can be removed once fixed.
        resource.add(
                linkTo(methodOn(CustomerController.class).getCustomerById(entity.getId())).withSelfRel());
        resource.add(linkTo(methodOn(CustomerController.class).getAllCustomers()).withRel("customers"));
        resource.add(linkTo(methodOn(CustomerController.class).getAddressesByCustomerId(entity.getId()))
                .withRel("self_addresses"));
        return resource;
    }

    /**
     * Converts the collection of Product entities to list of resources.
     *
     * @param entities
     * @return 
     */
    public List<Customer> toListModel(Iterable<CustomerEntity> entities) {
        if (Objects.isNull(entities)) {
            return List.of();
        }
        return StreamSupport.stream(entities.spliterator(), false).map(this::toModel).collect(toList());
    }

}
